# Site settings
title: Grobskizziert
email: fveitzen@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Wer nur auf das Kleine schaut, der verliert den Überblick.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://grobskizziert.de" # the base hostname & protocol for your site
twitter_username: realDogbert
github_username:  realDogbert

# Build settings
markdown: kramdown
